### ISSUE TITLE
Error Makefile:1: ../umbrella.mk:No such file or directory

### ISSUE THREAD

**Issue by artemliubymov** [gotthardp/rabbitmq-eiconv#1]
When i run make in directory "rabbitmq-eiconv" i got error : 
            Makefile:1: ../umbrella.mk:No such file or directory
             make: **\* No rule to make target «../umbrella.mk».  
How can i fix it?

**Comment by gotthardp** [comment]
Oh, sorry. The RabbitMQ was switched to another build system. To build eiconv against some 3.5.x RabbitMQ you need to explicitly checkout some older branch of the rabbitmq-umbrella by

```
$ ./foreachrepo git checkout <tag>
```

For example,

```
$ ./foreachrepo git checkout rabbitmq_v3_5_6
```

I updated the README.md accordingly. Please have a try and let me know.

**Comment by artemliubymov** [comment]
Yes, it worked, but i get another error when run make:
      ../common.mk:10: **\* GNU make version 3.81 required.

**Comment by gotthardp** [comment]
That sounds like you have an old version of GNU make. Are you able to upgrade? Which OS are you using?

**Comment by artemliubymov** [comment]
I using Ubuntu 15.04 and GNU make 4.0. I need to upgrade make?

**Comment by gotthardp** [comment]
No, this seems to be a rabbitmq issue. Could you please post the common.mk related error and the version related info you sent me to the rabbitmq-user list? They may suggest something.

**Comment by ArtemLubimov** [comment]
After i read your massage, i open common.mk and saw tha string:
    REQUIRED_MAKE_VERSION:=3.81
And than i change it to 4.0(my Make version) and run make in directory "rabbitmq-eiconv" i got this: 
   [elided] generate deps
[elided] fix test deps
sed -e 's|../coverage/build/deps.mk|$(DEPS_FILE)|' ../coverage/build/deps.mk > ../coverage/build/deps.mk.tmp && mv ../coverage/build/deps.mk.tmp ../coverage/build/deps.mk
[elided] generate deps
[elided] fix test deps
sed -e 's|build/deps.mk|$(DEPS_FILE)|' build/deps.mk > build/deps.mk.tmp && mv build/deps.mk.tmp build/deps.mk
rm -rf ./rabbitmq-eiconv-git
git clone https://github.com/zotonic/eiconv.git ./rabbitmq-eiconv-git
Cloning into './rabbitmq-eiconv-git'...
remote: Counting objects: 81, done.
remote: Total 81 (delta 0), reused 0 (delta 0), pack-reused 81
Unpacking objects: 100% (81/81), done.
Checking connectivity... готово.
# Work around weird github breakage (bug 25264)
cd ./rabbitmq-eiconv-git && git pull
Already up-to-date.
cd ./rabbitmq-eiconv-git && git checkout 644fb5e7bd6640fbd073f4d28957914ea979aea0
Note: checking out '644fb5e7bd6640fbd073f4d28957914ea979aea0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 644fb5e... Remove require_otp_vsn constraint, as we consider R13 obsolete.
find ./rabbitmq-eiconv-git -name "*.umbrella-orig" -delete
touch rabbitmq-eiconv-git/.done
echo UPSTREAM_SHORT_HASH:=`git --git-dir=./rabbitmq-eiconv-git/.git log -n 1 HEAD | grep commit | cut -b 8-14` >hash.mk
sed -n -e 's|^.*{vsn, *"\([^"]*\)".*$|ORIGINAL_VERSION:=\1|p' <rabbitmq-eiconv-git/src/eiconv.app.src >build/version.mk
[elided] generate deps
[elided] fix test deps
sed -e 's|build/deps.mk|$(DEPS_FILE)|' build/deps.mk > build/deps.mk.tmp && mv build/deps.mk.tmp build/deps.mk
rm -rf build/dep-ezs
mkdir -p build/dep-ezs
[elided] copy dependent ezs
touch build/dep-ezs/.done
rm -rf build/dep-apps
mkdir -p build/dep-apps
[elided] unzip ezs
touch build/dep-apps/.done
ERL_LIBS=./build/dep-apps erlc -Wall +debug_info -I ./include -I ./rabbitmq-eiconv-git/include -pa ebin -o ebin  rabbitmq-eiconv-git/src/eiconv.erl
ERL_LIBS=./build/dep-apps erlc -Wall +debug_info -I ./include -I ./rabbitmq-eiconv-git/include -pa ebin -o ebin  rabbitmq-eiconv-git/src/iconv.erl
sed -e 's|{vsn, *\"[^\"]*\"|{vsn,\"1.1-rmq0.0.0-git644fb5e\"|' <rabbitmq-eiconv-git/src/eiconv.app.src >build/eiconv.app.1.1-rmq0.0.0-git644fb5e
mkdir -p ./rabbitmq-eiconv-git/priv
gcc ./rabbitmq-eiconv-git/c_src/eiconv_nif.c -fpic -shared -I /usr/lib/erlang/usr/include -I /usr/local/lib/erlang/usr/include -o ./rabbitmq-eiconv-git/priv/eiconv_nif.so
rm -rf build/app
mkdir -p ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e/ebin ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e/include
[elided] copy beams to ebin
cp -p ./build/eiconv.app.1.1-rmq0.0.0-git644fb5e ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e/ebin/eiconv.app
cp -r ./rabbitmq-eiconv-git/priv ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e
touch build/app/.done.1.1-rmq0.0.0-git644fb5e
rm -rf dist
mkdir -p dist
cd ./build/app/ && zip -q -r /usr/lib/rabbitmq/lib/rabbitmq-public-umbrella/rabbitmq-eiconv/dist/eiconv-1.1-rmq0.0.0-git644fb5e.ez eiconv-1.1-rmq0.0.0-git644fb5e
touch dist/.done.1.1-rmq0.0.0-git644fb5e
touch dist/.done

This is right? If it doesn't, what can i do to help you fix this?

**Comment by artemliubymov** [comment]
After i read your massage, i open common.mk and saw tha string:
REQUIRED_MAKE_VERSION:=3.81
And than i change it to 4.0(my Make version) and run make in directory "rabbitmq-eiconv" i got this: 
'''
[elided] generate deps
[elided] fix test deps
sed -e 's|../coverage/build/deps.mk|$(DEPS_FILE)|' ../coverage/build/deps.mk > ../coverage/build/deps.mk.tmp && mv ../coverage/build/deps.mk.tmp ../coverage/build/deps.mk
[elided] generate deps
[elided] fix test deps
sed -e 's|build/deps.mk|$(DEPS_FILE)|' build/deps.mk > build/deps.mk.tmp && mv build/deps.mk.tmp build/deps.mk
rm -rf ./rabbitmq-eiconv-git
git clone https://github.com/zotonic/eiconv.git ./rabbitmq-eiconv-git
Cloning into './rabbitmq-eiconv-git'...
remote: Counting objects: 81, done.
remote: Total 81 (delta 0), reused 0 (delta 0), pack-reused 81
Unpacking objects: 100% (81/81), done.
Checking connectivity... готово.

# Work around weird github breakage (bug 25264)

cd ./rabbitmq-eiconv-git && git pull
Already up-to-date.
cd ./rabbitmq-eiconv-git && git checkout 644fb5e7bd6640fbd073f4d28957914ea979aea0
Note: checking out '644fb5e7bd6640fbd073f4d28957914ea979aea0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 644fb5e... Remove require_otp_vsn constraint, as we consider R13 obsolete.
find ./rabbitmq-eiconv-git -name "_.umbrella-orig" -delete
touch rabbitmq-eiconv-git/.done
echo UPSTREAM_SHORT_HASH:=`git --git-dir=./rabbitmq-eiconv-git/.git log -n 1 HEAD | grep commit | cut -b 8-14` >hash.mk
sed -n -e 's|^._{vsn, _"([^"]_)"._$|ORIGINAL_VERSION:=\1|p' <rabbitmq-eiconv-git/src/eiconv.app.src >build/version.mk
[elided] generate deps
[elided] fix test deps
sed -e 's|build/deps.mk|$(DEPS_FILE)|' build/deps.mk > build/deps.mk.tmp && mv build/deps.mk.tmp build/deps.mk
rm -rf build/dep-ezs
mkdir -p build/dep-ezs
[elided] copy dependent ezs
touch build/dep-ezs/.done
rm -rf build/dep-apps
mkdir -p build/dep-apps
[elided] unzip ezs
touch build/dep-apps/.done
ERL_LIBS=./build/dep-apps erlc -Wall +debug_info -I ./include -I ./rabbitmq-eiconv-git/include -pa ebin -o ebin  rabbitmq-eiconv-git/src/eiconv.erl
ERL_LIBS=./build/dep-apps erlc -Wall +debug_info -I ./include -I ./rabbitmq-eiconv-git/include -pa ebin -o ebin  rabbitmq-eiconv-git/src/iconv.erl
sed -e 's|{vsn, *\"[^\"]_\"|{vsn,\"1.1-rmq0.0.0-git644fb5e\"|' <rabbitmq-eiconv-git/src/eiconv.app.src >build/eiconv.app.1.1-rmq0.0.0-git644fb5e
mkdir -p ./rabbitmq-eiconv-git/priv
gcc ./rabbitmq-eiconv-git/c_src/eiconv_nif.c -fpic -shared -I /usr/lib/erlang/usr/include -I /usr/local/lib/erlang/usr/include -o ./rabbitmq-eiconv-git/priv/eiconv_nif.so
rm -rf build/app
mkdir -p ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e/ebin ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e/include
[elided] copy beams to ebin
cp -p ./build/eiconv.app.1.1-rmq0.0.0-git644fb5e ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e/ebin/eiconv.app
cp -r ./rabbitmq-eiconv-git/priv ./build/app/eiconv-1.1-rmq0.0.0-git644fb5e
touch build/app/.done.1.1-rmq0.0.0-git644fb5e
rm -rf dist
mkdir -p dist
cd ./build/app/ && zip -q -r /usr/lib/rabbitmq/lib/rabbitmq-public-umbrella/rabbitmq-eiconv/dist/eiconv-1.1-rmq0.0.0-git644fb5e.ez eiconv-1.1-rmq0.0.0-git644fb5e
touch dist/.done.1.1-rmq0.0.0-git644fb5e
touch dist/.done
'''

**Comment by artemliubymov** [comment]
Is this right? If it isn't, what i need to do, to help you fix this?

**Comment by gotthardp** [comment]
Yes, this looks right. There should be some .ez files in the /dist/ subdirectory. Are there?

**Comment by artemliubymov** [comment]
Yes, is there

**Comment by gotthardp** [comment]
Then it works fine. :-)

**Comment by artemliubymov** [comment]
O, Thank you very much!!!:)

**Comment by gotthardp** [comment]
Hi again, could you please do the following test to help debugging your issue?

In your common.mk, right after the line with REQUIRED_MAKE_VERSION, before the actual check, please add the following two lines, run make and post me the log message.

```
$(info MAKE_VERSION=$(MAKE_VERSION))
$(info $(shell ( echo "$(MAKE_VERSION)" ; echo "$(REQUIRED_MAKE_VERSION)" ) | sort -t. -n))
```

Thanks a bunch!

**Comment by artemliubymov** [comment]
Hi, i got this in log:
MAKE_VERSION=4.0
4.0 4.0
make: Цель «dist» не требует выполнения команд.
Or i need delete rabbitmq-eiconv and setup again?

2015-11-30 14:18 GMT+02:00 Petr Gotthard notifications@github.com:

**Comment by gotthardp** [comment]
Thanks, but-- could you please revert the change you made to the REQUIRED_MAKE_VERSION before you run it.

**Comment by artemliubymov** [comment]
MAKE_VERSION=4.0
4.0 3.81
../common.mk:13: **\* GNU make version 3.81 required.  Останов.

i got this

2015-11-30 18:10 GMT+02:00 Petr Gotthard notifications@github.com:

**Comment by gotthardp** [comment]
Thanks! Two more tests, please :)

Please execute

```
LANG="ru_RU.UTF-8" make
```

and then please post output from

```
printenv | grep "LC_"
printenv LANG
```

**Comment by artemliubymov** [comment]
LANG="ru_RU.UTF-8" make

   MAKE_VERSION=4.0
   3.81 4.0

printenv | grep "LC_"

   Nothing

printenv LANG

   ru_UA.UTF-8

2015-11-30 19:33 GMT+02:00 Petr Gotthard notifications@github.com:

**Comment by gotthardp** [comment]
Thanks a lot!
I escalated this as https://github.com/rabbitmq/rabbitmq-public-umbrella/issues/36

**Comment by gotthardp** [comment]
I'd actually need some testing ;-) Could you please use the original `common.mk` from rabbitmq_v3_5_6, but only add `LC_COLLATE=C` before `sort`?

The line 8 should read:

```
ifneq ($(shell ( echo "$(MAKE_VERSION)" ; echo "$(REQUIRED_MAKE_VERSION)" ) | LC_COLLATE=C sort -t. -n | head -1),$(REQUIRED_MAKE_VERSION))
```

**Comment by artemliubymov** [comment]
o yes, sorry i forgot to say that I for run
change REQUIRED_MAKE_VERSION:=3.81 to REQUIRED_MAKE_VERSION:=4.0. But when
I change native line 8 to your line(ifneq ($(shell ( echo "$(MAKE_VERSION)"
; echo "$(REQUIRED_MAKE_VERSION)" ) | LC_COLLATE=C sort -t. -n | head
-1),$(REQUIRED_MAKE_VERSION)))  It's work without any
changes REQUIRED_MAKE_VERSION

2015-12-05 23:26 GMT+02:00 Petr Gotthard notifications@github.com:

**Comment by gotthardp** [comment]
perfect! thanks a lot.
